### ISSUE TITLE
Can't start on Linux (Fedora 23)

### ISSUE THREAD

**Issue by unknownmx** [yeoman/yeoman-app#107]
The npm install dependencies fine, but when i start the app `npm start` one error appear:

```
Uncaught Exception:
Error: Cannot find module 'babel-runtime/core-js/object/get-prototype-of'
```

**Comment by stefanbuck** [comment]
That's strange. Please check if `babel-runtime` and all the dependency were installed successfully. Are you able to run babel in another context / project on Fedora 23?

**Comment by Chris2011** [comment]
Got the same of npm start on windows 10. NPM install ran without errors. I will check the babel thing again.

**Comment by Chris2011** [comment]
Fixed it via adding "babel-runtime": "6.6.1" as a dev dependency as someone mentioned it here: https://github.com/rblopes/generator-phaser-plus/issues/9#issuecomment-164318735

**Comment by Chris2011** [comment]
Added babel-core and babel-loader to it too, but this is what I did it before, didn't help. But babel-runtime worked. So please add it to the package.json in general.

**Comment by stefanbuck** [comment]
Thanks a lot for investigation in this issue. Would you like to create a PR for this?

**Comment by Chris2011** [comment]
I can but there is really no magic, it is only adding this line:
```
"babel-runtime": "6.6.1"
```

as a first entry into the devDependencies. Thats all.
