### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by ruyadorno** [yeoman/yeoman-app#14]
We can not postpone this anymore, the app needs serious unit and functional tests. We need to figure out:

- [x] ~~[Jest](https://facebook.github.io/jest/) unit tests for the front-end~~ Jasmine
- [x] How to add functional tests for atom-shell
- [x] How to have all tests running on Travis
- [ ] Add tests for renderer components

**Comment by stefanbuck** [comment]
l'll close this issue, because it's not a particular issue and in general we should aim to improving the test coverage with every single PR.
