### ISSUE TITLE
Stream yeoman logs to app

### ISSUE THREAD

**Issue by stefanbuck** [yeoman/yeoman-app#21]
The progress during npm and bower install is not visible for the user.

**Comment by ruyadorno** [comment]
not sure we want to stream anything from npm/bower install logs

these days npm switched to a progress bar for its install process, I don't think there's much to be shown to the user about it now - I'd certainly like to see a more user-friendly message along with the spinner but not the logs

**Comment by stefanbuck** [comment]
Yes, makes total sense. It was just a ruff idea to print the logs, but I totally agree with you.
