### ISSUE TITLE
Move the confirm button at the bottom?

### ISSUE THREAD

**Issue by pauldijou** [yeoman/yeoman-app#42]
Just wondering if there is any good reason to force the user to move back to the top of the page to confirm its answers when he reaches the bottom after completing them all.

**Comment by stefanbuck** [comment]
I agree, it's not ideal, but this solves in a way the scroll issue (see https://github.com/yeoman/yeoman-app/issues/47) :laughing: 

Joking aside, we should definitely consider the action button on the bottom of the page.

**Comment by ruyadorno** [comment]
@pauldijou do you have a particular generator that has a long stack of questions like that? It's going to be useful to test an implementation.

**Comment by ruyadorno** [comment]
Actually, I think that fixing #52 is a better fix for this issue, since if we only present one prompt at time there will never be the need to scroll down the page.
