### ISSUE TITLE
Radio buttons not working for me

### ISSUE THREAD

**Issue by pauldijou** [yeoman/yeoman-app#43]
All of the radio buttons generated from prompts `type: list` are not working with the following JS error in the console:

```
[6016:0726/125628:INFO:CONSOLE(28)] "Uncaught TypeError: Cannot read property 'value' of null", source: .../yeoman-app/src/renderer/components/prompts/list.jsx (28)
```

**Comment by stefanbuck** [comment]
The issues is now part of the Beta roadmap. Thanks for reporting :+1:

**Comment by bitshadow** [comment]
I had the same error. Hopefully #74 should fix it.

**Comment by stefanbuck** [comment]
It works fine but unless the `choices` attribute is an array, it will not work. It's a general problem so we should fix it for all affected prompt types.
