### ISSUE TITLE
[Inquiry] Why was babel removed?

### ISSUE THREAD

**Issue by mfunkie** [yeoman/yeoman-app#44]
I noticed in this changeset from May that Babel was removed as a dependency:

https://github.com/yeoman/yeoman-app/commit/7abf463e6764a0b63968b7ac8006e1482d007526

Per http://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html
the React JSTransform is being deprecated, which is what node-jsx uses to transform code.

**Comment by sindresorhus** [comment]
Can't answer why it was removed, but we should just use [`electron-precompile`](https://github.com/paulcbetts/electron-compile) and use ES2015 for everything.

**Comment by mfunkie** [comment]
Sounds good to me.  I can look at adding it over the next few days if no one objects or gets to it first.

**Comment by sindresorhus** [comment]
@ruyadorno @stefanbuck You good with that?

**Comment by stefanbuck** [comment]
I'm totally fine with it. I removed babel, because we didn't used any ES2015 feature at this point. But you are right, we should definitely start writing ES2015 coe. 

@mfunkie  a PR is always welcome :+1:

**Comment by ruyadorno** [comment]
just for the record, I also completely agree :+1: 

@mfunkie's PR is on the way so I'm closing this one, thanks!
