### ISSUE TITLE
App fails to open on mac os 10.8.5

### ISSUE THREAD

**Issue by jeanmichelcote** [yeoman/yeoman-app#57]
## `Yeoman quit unexpectedly`

Build process succeeds although when the app is launched, the `Yeoman quit unexpectedly` window appears before anything else.

Let me know what i can do to help.

**Comment by stefanbuck** [comment]
Can you start the app via `npm start`?

**Comment by jeanmichelcote** [comment]
It starts and then kills itself after 4 seconds. But this appears:

`> yeoman-app@0.0.0 start /Users/me/yeoman/yeomanapp/yeoman-app
> electron .`

**Comment by jeanmichelcote** [comment]
Hum, i may have to install electron first...

**Comment by ruyadorno** [comment]
not really, usually you just need to run `npm install` and `npm start` should work

**Comment by jeanmichelcote** [comment]
Ok, so it really doesn't work then.

**Comment by jeanmichelcote** [comment]
Would it help you guys to take a peek at the apple crash report?

**Comment by ruyadorno** [comment]
you might also try:
- `rm -rf node_modules`
- `npm cache clean`
- `npm install`
- `npm start`

**Comment by jeanmichelcote** [comment]
Did what you suggested; same result.

**Comment by jeanmichelcote** [comment]
Should i delete the whole build and rebuild it right after?

**Comment by stefanbuck** [comment]
Please fetch the latest changes from the master and run `npm install` again. Maybe `electron-compile` will fix the problem

**Comment by jeanmichelcote** [comment]
I fetched with `git pull`, then `npm install`, then `npm start`.
Same result:

yeoman-app@0.0.0 start /Users/me/yeoman/yeomanapp/yeoman-app
electron . -r

**Comment by stefanbuck** [comment]
Are you familiar with C and code compiling? If so, you can use [crashpad](https://github.com/atom/crashpad) to get the crash report.

**Comment by jeanmichelcote** [comment]
A bit. Probably just enough. 
But i mainly use sublime as a text editor.

Ok, i'll try to get the crash report.

**Comment by stefanbuck** [comment]
This is useful to getting started with crashpad. https://github.com/atom/crashpad/blob/master/doc/developing.ad#L51-L93

**Comment by jeanmichelcote** [comment]
Ok thanks. Will check it out this evening and will come back here as soon as i get a decent report.

**Comment by jeanmichelcote** [comment]
Ok, so i am a newbie in that field. But still, why not use this in the `main.js` file?

`// Report crashes to our server.
require('crash-reporter').start();`

**Comment by stefanbuck** [comment]
By default  `crash-reporter` will send all reports to GitHub's crash report server. Of course we should enabled it, but I don't think we will get access to it. Ideally we would have our own crash report server ...  someday.

https://github.com/atom/electron/blob/master/docs/api/crash-reporter.md

**Comment by jeanmichelcote** [comment]
Good idea.
So now i am a little lost as of how to use crashpad to get the report. Should i download chromium? Should i open an Xcode project? Why were you asking me if i am confortable with C? 

I am just starting so i need to set myself upon a solid base to go further.

**Comment by stefanbuck** [comment]
You have to follow the build instructions to get an executable version of crashpad. First make sure that you have all dependencies installed [depottols](https://dev.chromium.org/developers/how-tos/depottools) [gyp](https://gyp.googlecode.com/) and [Ninja](https://martine.github.io/ninja/). Hope this helps a bit

**Comment by stefanbuck** [comment]
Hi, I've created a basic crash report server to get the crash reports from the app.

Clone the repo and run `npm install` + `npm start`.
https://github.com/stefanbuck/electron-crash-reporter-server

Copy this to the `main.js` and run the app via `npm start`.
```
var crashReporter = require('crash-reporter');
crashReporter.start({
  productName: 'Yeoman-App',
  companyName: 'Yeoman Team',
  submitUrl: 'http://127.0.0.1:3000/',
  autoSubmit: true
});
```

**Comment by jeanmichelcote** [comment]
Good, I'll try that. Should i download the repo somewhere in particular?

And when you `require('crash-reporter')` in the small snippet that needs to be added to the main.js file, the `crash-reporter` file should be somewhere in the filesystem, right? Yours is called `electron-crash-reporter-server`, is it supposed to be the one? Aren't they supposed to have the same name?

Sorry about this, I need to understand what's about it all...

**Comment by stefanbuck** [comment]
> Should i download the repo somewhere in particular?

No, just run it and the app will sent all reports to this local running server.

> crash-reporter file should be somewhere in the filesystem, right? Yours is called electron-crash-reporter-server, is it supposed to be the one? 

No, `crash-reporter` is part of the electron API so it's embedded in the core like `fs` or `path`. `electron-crash-reporter-server` is just a random pick up name for the package.

**Comment by jeanmichelcote** [comment]
Ok thanks.

So i started your server and went to localhost:3000. This was showing at the top of the page:

`{"statusCode":404,"error":"Not Found"}`

and in the console:

`Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by jeanmichelcote** [comment]
I restarted it and now still showing:
`{"statusCode":404,"error":"Not Found"}`
at the top but in the console, everything looked fine.

**Comment by jeanmichelcote** [comment]
So first i npm start your electron server, than i npm start the yeoman app?

**Comment by ruyadorno** [comment]
I think I have an osx 10.8.x at home, I'll try running the app on it and see if I can reproduce the problem

**Comment by stefanbuck** [comment]
> So first i npm start your electron server, than i npm start the yeoman app?

Correct, the app should send reports to the server if something goes wrong. Did you get something (error or information message) in the server log ?

**Comment by jeanmichelcote** [comment]
Nothing at all. 
But I just installed crashpad and tested it positive. I just need to know now how it works.

**Comment by bitshadow** [comment]
Same happens for me as well with osx 10.9.4. With Yosemite works fine though. Probably #53.  

![screen shot 2015-08-01 at 9 59 55 am](https://cloud.githubusercontent.com/assets/574802/9020602/28ee4d3e-3834-11e5-849f-8f750184af37.png)

**Comment by minhhh** [comment]
Same thing happens to me with OSX 10.9.5.

**Comment by jeanmichelcote** [comment]
@minhhh How did you get that error output?

**Comment by stefanbuck** [comment]
@jeanmichelcote @minhhh @bitshadow please check out  https://github.com/sindresorhus/electron-boilerplate to verify if this is an issue with the yeoman-app or electron itself. Thank you

**Comment by stefanbuck** [comment]
... you can use this sample app https://github.com/stefanbuck/-electron-compile-boilerplate

**Comment by bitshadow** [comment]
Looks like electron-compile-boilerplate is working for me in 10.9.4. :+1: 

![screen shot 2015-08-04 at 12 01 20 pm](https://cloud.githubusercontent.com/assets/574802/9054589/a734d82a-3aa0-11e5-8b1f-14b38f0943f3.png)

**Comment by jeanmichelcote** [comment]
Sorry guys, i got the exact same terminal output either from  @sindresorhus  boilerplate nor @stefanbuck  superb app:

`> yeoman-app@0.0.0 start /Users/me/public/yeoman/electron-boilerplate`
` > electron . -r`
and
`> yeoman-app@0.0.0 start /Users/me/public/yeoman/electron-compile-boilerplate`
` > electron . -r`

and then back to prompt after 2 seconds.

i have reinstalled `npm install electron-prebuilt -g`, still the same results.

**Comment by ThomasCrvsr** [comment]
I had the same problem with OSX 10.9.5 , apparently launching `electron .` instead of `electron . -r` did the trick.

**Comment by stefanbuck** [comment]
> I had the same problem with OSX 10.9.5 , apparently launching electron . instead of electron . -r did the trick.

 @jeanmichelcote @bitshadow @minhhh is this working for you?

**Comment by jeanmichelcote** [comment]
As i was saying in my last post:

if i just `electron .` instead of `npm start` in the main directory, i got those errors:

`[0804/090959:ERROR:http_transport_mac.mm(186)] Could not connect to the server. (NSURLErrorDomain -1004)
[0804/091001:WARNING:crash_report_exception_handler.cc(247)] UniversalExceptionRaise com.apple.ReportCrash: (ipc/mig) server died (0xfffffecc)`

**Comment by stefanbuck** [comment]
Sounds like a bug in `electron` or `electron-prebuilt`. You are not the only one with this behaviour https://github.com/mafintosh/electron-prebuilt/issues/42

Please continue there to support them. Thanks

**Comment by bitshadow** [comment]
@stefanbuck `electron .` it did not work. But patching up chalk worked for me.

I commented this line in `node_modules` and its no longer checking if tty is available or not. 
`node_modules/electron-compile/node_modules/electron-compilers/node_modules/babel-core/node_modules/chalk/node_modules/supports-color/index.js:29`

Its a hack though but If you have better option please let me know.

**Comment by stefanbuck** [comment]
Looks like an issue in electron. I've created an issue https://github.com/atom/electron/issues/2432
