### ISSUE TITLE
Update Flux implementation

### ISSUE THREAD

**Issue by ruyadorno** [yeoman/yeoman-app#61]
> Continuing the discussion from #53 ...

I think working to update the overall Front-end/React architecture is the most important thing to do next :+1: 

While discussing about the project with friends at work, some people were suggesting to implement some React framework in order to improve the overall organization and avoid the verbosity we have right now.

@davidzzhang is one of the smart guys here at work that suggested the use of [redux](https://github.com/gaearon/redux), maybe he can give us some advice / share some ideas.

@mfunkie what do you think about picking a framework? if that's the case, is **redux** good enough?

/cc @stefanbuck

**Comment by mfunkie** [comment]
I'm so happy you mentioned Redux! I was just going to use vanilla flux to not cause a clash of ideals, but I really like what Redux is doing.  1.0 is very soon, so we can start work based off of it and it will more than likely be released before us.

**Comment by davidzzhang** [comment]
Glad you guys are giving redux a chance! Should be able to cut down so much boilerplate and explicit dependencies, and the stateless stores will do wonders for testing.

I actually tried to see if I could take a crack at incorporating redux, but realized there's quite a bit to learn about this codebase before that's possible. :P Still, I'm happy to help out if there's anything I can do.

**Comment by stefanbuck** [comment]
To be honest I'm not experienced with Redux and React at all, but I'm more than happy to start with the newest fancy shit :rocket:

**Comment by mfunkie** [comment]
I've written production apps with both vanilla Flux and Alt (a flux implementation).  I think Redux is probably the way to go for future endeavors.  I'll try and tackle this when I have some free time.

**Comment by donaldpipowitch** [comment]
I'm just curious: has someone already tried Cycle.js instead of React with a Flux framework? It looks ideal for this project.
