### ISSUE TITLE
With wrong colour generation, generator is unreadable

### ISSUE THREAD

**Issue by keirlawson** [yeoman/yeoman-app#62]
When yeoman-app randomly picks a dark gray the resulting experience is pretty bad:

![yeoman-unreadable](https://cloud.githubusercontent.com/assets/49213/8961157/827ced68-360b-11e5-9864-0d472579fb7a.png)

**Comment by ruyadorno** [comment]
We need a better solution for picking up colors.

There's an even worst related problem that I was able to reproduce sometimes, if you try to run a generator that got assigned the **white** color it doesn't work at all :dizzy_face:

**Comment by stefanbuck** [comment]
I added a black list to exclude problematic colours like white and back. Maybe we should add more shades of black and white. 

https://github.com/yeoman/yeoman-app/blob/0ce754609715ba0e8e4ba6e0b22e3ee0bceb35da/src/renderer/utils/colors.js#L8

**Comment by ruyadorno** [comment]
ah, that's a great solution! we just need to add the problematic colors we find to this list!
