### ISSUE TITLE
Running without the SUID sandbox!

### ISSUE THREAD

**Issue by danilosampaio** [yeoman/yeoman-app#67]
when i start yeoman-app, it shows the following error in console:

`[4906:0805/205203:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.`

Nevertheless, the app runs fine.

should i worry about this error?

P.S. i'm running it in ubuntu 15.04.

**Comment by danilosampaio** [comment]
Apparently, it can be ignored:

https://github.com/atom/electron/issues/1482

**Comment by stefanbuck** [comment]
Thanks for adding the reference.
