### ISSUE TITLE
Convert existing components to ES6 classes

### ISSUE THREAD

**Issue by mawie81** [yeoman/yeoman-app#69]
Hi,

I just found out that there is alreay one component (https://github.com/yeoman/yeoman-app/blob/master/src/browser/application.js) using ES6 classes while others don´t.

So I just went ahead and converted the AppWindow and one React component to ES6.
This work out fine with one tiny problem: The tests break :-(
I think this is because they just use jasmine which doesn´t like ES6.

The question now is: should the app be converted to ES6 and if so how to tackle the tests?

**Comment by ruyadorno** [comment]
> should the app be converted to ES6

@mawie81 the answer is YES, the plan is to convert the entire app to ES6. 

For the sake of getting easier/faster to merge PRs please don't submit a single PR converting everything at once, let's do it a couple of classes at time (it seems to be your approach but I just want to make it clear for other people that might want to jump in).

> and if so how to tackle the tests

@stefanbuck do you have a better idea on how to handle that?

**Comment by stefanbuck** [comment]
I didn't know that Jasmine doesn't work with ES2015, that's bad. Personally I like Mocha but I think it's time to give [Jest](https://facebook.github.io/jest/docs/api.html) a try. Has somebody experience with it?

**Comment by ruyadorno** [comment]
@mfunkie converted the react components while working on implementing [redux](https://github.com/rackt/redux): #76 

We still need to tackle the tests but let's focus on tracking the progress on #14
