### ISSUE TITLE
"Uncaught (in promise) TypeError: Cannot read property 'x' of null"

### ISSUE THREAD

**Issue by HeshamAbdalla** [yeoman/yeoman-app#88]
The error is from the terminal while running npm start.

Also the Yeoman app never open and automagically open the dev tool and I saw those errors.

_materialUi2.default.Styles.themeManager is not a function.

in node_modules/less/dist/less.js, xhr.open('GET', url, async); is throwing Synchronous error.

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.

**Comment by onlyskyguy** [comment]
Same issue on Xubuntu 15.10

**Comment by ruyadorno** [comment]
:+1: thanks for reporting, most likely a `material-ui` update issue

**Comment by HeshamAbdalla** [comment]
No problems that's what I thought.
