### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by ruyadorno** [yeoman/yeoman-app#96]
While working on #95 I found out that `npm run build` is not really working as expected. To make sure it wasn't a problem with the **electron** related updates I went on and tested on `master` and got the same results.

@stefanbuck do you believe you might have some time to take a look? :eyes:

**Comment by stefanbuck** [comment]
Mhhh that's strange. The build was successful and the app is executable. Can you provide more details what exactly is not working for you?

**Comment by ruyadorno** [comment]
On current `master`:

```
npm run build

> yeoman-app@0.0.0 build /Users/ruy.adorno/Documents/workspace/yeoman-app
> electron-compile --target ./cache src/ static/ && node scripts/build.js

Packaging app for platform darwin x64 using electron v0.33.7
Build task completed.

open build/darwin/x64/Yeoman-darwin-x64/Yeoman.app
```

This is what I get:

<img width="800" alt="screen shot 2016-01-17 at 12 54 54 pm" src="https://cloud.githubusercontent.com/assets/220900/12378872/bed871ac-bd19-11e5-8c83-3c1fb655773e.png">

**Comment by stefanbuck** [comment]
I was able to build the app from current master on all my computers. Can you please verify this again, just to be sure?

**Comment by stefanbuck** [comment]
Did you delete `.cache` and `node_modules` folder upfront?

**Comment by ruyadorno** [comment]
it seems my issues were either related to not cleaning the `.cache` folder or related to the existence of an `apm` folder that was present in the project root - probably a leftover from old configs

anyways, a clean start fixed it, thanks @stefanbuck
