### ISSUE TITLE
Remove less, use inline styling instead

### ISSUE THREAD

**Issue by ruyadorno** [yeoman/yeoman-app#97]
We're already halfway through the effort.

**Comment by 4tron** [comment]
wait what? why would you use inline styling?!?!?!

**Comment by SBoudrias** [comment]
@4tron I think by that Ruy meant CSS through JS with react.

**Comment by 4tron** [comment]
@SBoudrias ok i have not used react so maybe i am not understanding this correctly.

**Comment by SBoudrias** [comment]
@4tron some references:

https://facebook.github.io/react/tips/inline-styles.html
https://medium.com/@jviereck/modularise-css-the-react-way-1e817b317b04

**Comment by 4tron** [comment]
Oh wow ... ok .. so people actually develop like that? That is interesting.

**Comment by ruyadorno** [comment]
thanks @SBoudrias, that's exactly it :blush: 

@4tron the main reason behind this is that we want to follow the same conventions from the ui library that we use for our visual components - that library is [material-ui](http://www.material-ui.com/). They did started out with using LESS and eventually migrated to styles within JSX.
